### ISSUE TITLE
Why are we breaking stuffs when developing?

### ISSUE THREAD

**Issue by sagaragarwal94** [fosslnmiit/fosslnmiit-website#26]
Forgot password not working
Updation not working
Font issues
@sonali0901 and @hiteshgarg14 do have look, before push

**Comment by sagaragarwal94** [comment]
logout and login not working 😭

**Comment by hiteshgarg14** [comment]
There was an error related to code. now website is live

**Comment by shivammathur** [comment]
As it is fixed, marking invalid and closing it.
