### ISSUE TITLE
Add a method to close this `info` status.

### ISSUE THREAD

**Issue by kiok46** [fosslnmiit/fosslnmiit-website#27]
Either add a cross button for user to manually remove it or bind some event to close it when the user verifies the account.

<img width="1437" alt="screen shot 2016-09-03 at 2 20 53 pm" src="https://cloud.githubusercontent.com/assets/7335120/18223848/9e946888-71e1-11e6-8749-7bb366a504b5.png">

image ^^^

**Comment by manthansharma** [comment]
can use bootstrap alert box for info message

**Comment by sagaragarwal94** [comment]
Solved :)
