### ISSUE TITLE
Some pages not responsive on small screen

### ISSUE THREAD

**Issue by manthansharma** [fosslnmiit/fosslnmiit-website#29]
Home Page
<img width="368" alt="screen shot 2016-09-03 at 6 47 37 pm" src="https://cloud.githubusercontent.com/assets/14853016/18225031/04d84e8c-7207-11e6-84dd-0b55e192532a.png">

Element out of body tag in small screen.

**Comment by shivammathur** [comment]
Closing as solved here #30
