### ISSUE TITLE
Mobile view enhancement

### ISSUE THREAD

**Issue by Tabs16** [fosslnmiit/fosslnmiit-website#31]
Mobile view of the website needs improvement , landing page is not shown properly @hiteshgarg14

**Comment by sagaragarwal94** [comment]
@Tabs16 Assigned :)

**Comment by sagaragarwal94** [comment]
@Tabs16 
Create the PR and Send to main branch :)

**Comment by sagaragarwal94** [comment]
#33 The code is here . @hiteshgarg14 Have a look. I am merging the PR.
Thanks @Tabs16

**Comment by hiteshgarg14** [comment]
Mobile view of Events and Contribution Pages still needs improvement. @Tabs16
