### ISSUE TITLE
User with valid .lnmiit.ac.in can sign up. 

### ISSUE THREAD

**Issue by sagaragarwal94** [fosslnmiit/fosslnmiit-website#5]
No other user apart from this extension can sign up. Must have .lnmiit.ac.in.

**Comment by mayank-agarwal-96** [comment]
I think , it would be better if there is an email verification after checking if lnmiit.ac.in is present or not. What do you think?

**Comment by hiteshgarg14** [comment]
@mayank-agarwal-96 see issue #3

**Comment by mayank-agarwal-96** [comment]
Oh, I didn't see that.

**Comment by sagaragarwal94** [comment]
Already merged.
